version: '3.7'

services:
  webapp:
    build: webapp/
    ports:
      - "3000:3000"
    volumes:
      - ./webapp/src:/app/src
      - ./webapp/public:/app/public
      - ./webapp/package.json:/app/package.json
      - ./webapp/package-lock.json:/app/package-lock.json
